### ISSUE TITLE
Create New User - User Administration Portal Error

### ISSUE THREAD

**Issue by noFAYZ** [uPortal-Project/uPortal-start#506] opened 2021-02-20 01:56 UTC
I cannot be able to add new users from User Administration portal and getting this null pointer exception

1. Fresh Install uPortal-start
2. Click on 'User Administration portal'
3. Add user details and Save

**Screenshots**

![Capture](https://user-images.githubusercontent.com/57537470/108579382-6dafa800-7348-11eb-94d1-960d88dfaf8f.PNG)

**Platform:**
 - uPortal Version: [ uPortal 5.1]
 - OS: [Cent OS 7]
 - Browser [Chrome,]

**Comment by noFAYZ** [comment] 2021-02-22 02:31
That's a Bug its on every fresh install

**Comment by jonathanmtran** [comment] 2021-02-23 04:31
Duplicate of uPortal-Project/uPortal#2258

**Closed by jonathanmtran** 2021-02-23 04:31 UTC
